name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout the repository
        uses: "actions/checkout@v4"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
        with:
          path: ./custom_components/xweather

